apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
spec:
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image:  zigzigcheers/todo:{{.Tag}}
          ports:
          - containerPort: 8080
          resources:
            limits:
              memory: 1024Mi
              cpu: '2'
            requests:
              memory: 64Mi
              cpu: '0.5'
          env:
            - name:  HELLO
              value: {{.HELLO}}

---
apiVersion: v1
kind: Service
metadata:
  name:  todo-service
spec:
  selector:
    app: todo
  type: LoadBalancer
  ports:
  - port: 8080