apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
spec:
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image:  zigzigcheers/todo:{{tag}}
          ports:
          - containerPort: 8080
          resources:
            limits:
              memory: 1024Mi
              cpu: '2'
            requests:
              memory: 64Mi
              cpu: '0.5'
          # env:
            # - name:  MONGO_USERNAME
            #   valueFrom:
            #     secretKeyRef:
            #       name:  todo-secret
            #       key: mongo_username
            # - name:  MONGO_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name:  todo-secret
            #       key: mongo_password
            # - name:  MONGO_SERVER
            #   valueFrom:
            #     configMapKeyRef:
            #       name:  todo-configmap
            #       key: mongo_server

---
apiVersion: v1
kind: Service
metadata:
  name:  todo-service
spec:
  selector:
    app: todo
  type: LoadBalancer
  ports:
  - port: 8080